services:

  postgres:
    image: postgres:17.4
    container_name: auth-server-postgres
    environment:
      POSTGRES_DB: auth_server
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_server"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-server:
    image: oauth2-auth-server
    container_name: auth-server
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_server
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_healthy