server:
  port: 8080

spring:
  application:
    name: oidc-simple-client

credentials:
  users:
    - user1:
      login: "john@mail.com"
      password: "pass"
      roles:
        - ADMIN

oauth:
  clients:
    - client1:
      id: oauth2-simple-client
      secret: secret2
      registrationId: oauth2-simple-client
      name: oauth2-simple-client
      redirectUrl: http://127.0.0.1:8080/login/oauth2/code/oauth2-simple-client
      authorizationUrl: http://auth.local:9000/oauth2/authorize
      tokenUrl: http://auth.local:9000/oauth2/token
      userInfoUrl: http://auth.local:9000/userinfo
      jwksUrl: http://auth.local:9000/oauth2/jwks


logging:
  level:
    '[org.springframework.security]': TRACE