
spring:
  application:
    name: auth-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_server
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9000

app:
  token:
    access-ttl: 2m
    refresh-ttl: 10d
